# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute vqtilde — denominator of the MV outlier statistic
#'
#' For each marker row of \code{trans}, computes
#' \code{tr(Ginv \%*\% (Ti \%*\% vatilde \%*\% t(Ti)))} where
#' \code{Ti = kronecker(diag(ntrait), trans[k,,drop=FALSE])}.
#' This is the denominator of the multivariate outlier statistic
#' \eqn{t^2_{kl}} from Verbyla & Cullis (2012), equation (11).
#'
#' @param trans   nmarkers x nlines back-transform matrix M^T(MM^T)^{-1}.
#' @param Ginv    ntrait x ntrait generalised inverse of Ga.
#' @param vatilde (ntrait*nlines) x (ntrait*nlines) posterior variance
#'   (Ga x relm - PEV), arranged in trait-major block order.
#' @param ntrait  Number of traits/environments.
#' @return Numeric vector of length nmarkers.
#' @keywords internal
compute_vqtilde <- function(trans, Ginv, vatilde, ntrait) {
    .Call(`_wgAim_compute_vqtilde`, trans, Ginv, vatilde, ntrait)
}

